# CA1 Statistical Techniques for Data Analysis

Dataset: **Data_CA1.csv** - an anonymous survey with 41 responses to 18 questions on the leisure travel habits of people living in Ireland.

The survey was run as a Google Form: https://docs.google.com/forms/d/e/1FAIpQLSdrzDmbAsnr-aCScCQZNd7D6rMeA9Rdp513igdLuxQqrRo2Ow/viewform?usp=dialog

The data was collected for academic purposes and has been fully anonymised (timestamps were also removed, as they are a potential way to de-anonymise responses).

## 0. Import libraries

In [1]:
# Import required libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

## 1. Load & clean the data

### 1.1 Load and look at the dataset

In [2]:
# Load the dataset
df = pd.read_csv('Data_CA1.csv')

In [3]:
# Take a look at the dataset
df.head()

,Unnamed: 0,Total score,1. What is your gender?,1. What is your gender? [Score],1. What is your gender? [Feedback],2. What is your age?,2. What is your age? [Score],2. What is your age? [Feedback],3. How long have you been living in Ireland?,3. How long have you been living in Ireland? [Score],...,15. What is your preferred way of travelling around Ireland? [Feedback],16. What is the typical length of your leisure trip within Ireland?,16. What is the typical length of your leisure trip within Ireland? [Score],16. What is the typical length of your leisure trip within Ireland? [Feedback],17. Which counties in Ireland have you visited for leisure?,17. Which counties in Ireland have you visited for leisure? [Score],17. Which counties in Ireland have you visited for leisure? [Feedback],"18. Overall, how satisfied are you with the opportunities to explore Ireland?","18. Overall, how satisfied are you with the opportunities to explore Ireland? [Score]","18. Overall, how satisfied are you with the opportunities to explore Ireland? [Feedback]"
0,0,0.00 / 0,Male,-- / 0,NaN,27,-- / 0,NaN,3 - 4 years,-- / 0,...,NaN,4 - 7 nights,-- / 0,NaN,Cork;Donegal;Dublin;Galway;Kerry;Kildare;Kilke...,-- / 0,NaN,5,-- / 0,NaN
1,1,0.00 / 0,Male,-- / 0,NaN,28,-- / 0,NaN,I was born in Ireland,-- / 0,...,NaN,One day/ No overnight stay,-- / 0,NaN,Cork;Dublin;Kildare,-- / 0,NaN,5,-- / 0,NaN
2,2,0.00 / 0,Male,-- / 0,NaN,55,-- / 0,NaN,I was born in Ireland,-- / 0,...,NaN,2 - 3 nights,-- / 0,NaN,Cork;Donegal;Dublin;Galway;Kerry;Mayo;Sligo;We...,-- / 0,NaN,4,-- / 0,NaN
3,3,0.00 / 0,Female,-- / 0,NaN,29,-- / 0,NaN,I was born in Ireland,-- / 0,...,NaN,2 - 3 nights,-- / 0,NaN,Carlow;Clare;Cork;Donegal;Dublin;Galway;Kildar...,-- / 0,NaN,3,-- / 0,NaN
4,4,0.00 / 0,Female,-- / 0,NaN,29,-- / 0,NaN,I was born in Ireland,-- / 0,...,NaN,2 - 3 nights,-- / 0,NaN,Carlow;Clare;Cork;Donegal;Dublin;Galway;Kildar...,-- / 0,NaN,3,-- / 0,NaN

In [4]:
df.shape

(41, 56)

In [5]:
df.describe()

,Unnamed: 0,1. What is your gender? [Feedback],2. What is your age?,2. What is your age? [Feedback],3. How long have you been living in Ireland? [Feedback],4. Which county do you currently live in? [Feedback],5. What best describes your current living area? [Feedback],6. What is your household situation? [Feedback],7. Do you have a car in Ireland? [Feedback],8. Would you prefer to spend next holiday in Ireland or abroad? [Feedback],...,11. Who do you usually travel with? [Feedback],12. What is the main purpose of your leisure trips? [Feedback],13. How many leisure trips within Ireland have you taken in the last 12 months?,13. How many leisure trips within Ireland have you taken in the last 12 months? [Feedback],14. What type of Irish destination do you prefer? [Feedback],15. What is your preferred way of travelling around Ireland? [Feedback],16. What is the typical length of your leisure trip within Ireland? [Feedback],17. Which counties in Ireland have you visited for leisure? [Feedback],"18. Overall, how satisfied are you with the opportunities to explore Ireland?","18. Overall, how satisfied are you with the opportunities to explore Ireland? [Feedback]"
count,41.000000,0.0,41.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,41.000000,0.0,0.0,0.0,0.0,0.0,41.000000,0.0
mean,20.000000,NaN,34.804878,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2.731707,NaN,NaN,NaN,NaN,NaN,4.024390,NaN
std,11.979149,NaN,6.918163,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,3.535706,NaN,NaN,NaN,NaN,NaN,0.851111,NaN
min,0.000000,NaN,26.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,3.000000,NaN
25%,10.000000,NaN,29.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,3.000000,NaN
50%,20.000000,NaN,33.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2.000000,NaN,NaN,NaN,NaN,NaN,4.000000,NaN
75%,30.000000,NaN,39.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,NaN,5.000000,NaN
max,40.000000,NaN,55.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,NaN,5.000000,NaN

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 56 columns):
 #   Column                                                                                                      Non-Null Count  Dtype
---  ------                                                                                                      --------------  -----
 0   Unnamed: 0                                                                                                  41 non-null     int64
 1   Total score                                                                                                 41 non-null     str
 2   1. What is your gender?                                                                                     41 non-null     str
 3   1. What is your gender? [Score]                                                                             41 non-null     str
 4   1. What is your gender? [Feedback]                                                                          0 non-null      float64
 5   2. What is your age?                                                                                        41 non-null     int64
 6   2. What is your age? [Score]                                                                                41 non-null     str
 7   2. What is your age? [Feedback]                                                                             0 non-null      float64
 8   3. How long have you been living in Ireland?                                                                41 non-null     str
 9   3. How long have you been living in Ireland?  [Score]                                                       41 non-null     str
 10  3. How long have you been living in Ireland?  [Feedback]                                                    0 non-null      float64
 11  4. Which county do you currently live in?                                                                   41 non-null     str
 12  4. Which county do you currently live in?  [Score]                                                          41 non-null     str
 13  4. Which county do you currently live in?  [Feedback]                                                       0 non-null      float64
 14  5. What best describes your current living area?                                                            41 non-null     str
 15  5. What best describes your current living area? [Score]                                                    41 non-null     str
 16  5. What best describes your current living area? [Feedback]                                                 0 non-null      float64
 17  6. What is your household situation?                                                                        41 non-null     str
 18  6. What is your household situation? [Score]                                                                41 non-null     str
 19  6. What is your household situation? [Feedback]                                                             0 non-null      float64
 20  7. Do you have a car in Ireland?                                                                            41 non-null     str
 21  7. Do you have a car in Ireland? [Score]                                                                    41 non-null     str
 22  7. Do you have a car in Ireland? [Feedback]                                                                 0 non-null      float64
 23  8. Would you prefer to spend next holiday in Ireland or abroad?                                             41 non-null     str
 24  8. Would you prefer to spend next holiday in Ireland or abroad? [Score]                                     41 non-null     str
 25  8. Would you prefer to spend next holiday in Ireland or abroad? [Feedback]                                  0 non-null      float64
 26  9. How many leisure trips have you taken in the last 12 months, both within Ireland and abroad?             41 non-null     int64
 27  9. How many leisure trips have you taken in the last 12 months, both within Ireland and abroad? [Score]     41 non-null     str
 28  9. How many leisure trips have you taken in the last 12 months, both within Ireland and abroad? [Feedback]  0 non-null      float64
 29  10. What type of leisure trip do you prefer?                                                                41 non-null     str
 30  10. What type of leisure trip do you prefer? [Score]                                                        41 non-null     str
 31  10. What type of leisure trip do you prefer? [Feedback]                                                     0 non-null      float64
 32  11. Who do you usually travel with?                                                                         41 non-null     str
 33  11. Who do you usually travel with? [Score]                                                                 41 non-null     str
 34  11. Who do you usually travel with? [Feedback]                                                              0 non-null      float64
 35  12. What is the main purpose of your leisure trips?                                                         41 non-null     str
 36  12. What is the main purpose of your leisure trips? [Score]                                                 41 non-null     str
 37  12. What is the main purpose of your leisure trips? [Feedback]                                              0 non-null      float64
 38  13. How many leisure trips within Ireland have you taken in the last 12 months?                             41 non-null     int64
 39  13. How many leisure trips within Ireland have you taken in the last 12 months?  [Score]                    41 non-null     str
 40  13. How many leisure trips within Ireland have you taken in the last 12 months?  [Feedback]                 0 non-null      float64
 41  14. What type of Irish destination do you prefer?                                                           41 non-null     str
 42  14. What type of Irish destination do you prefer? [Score]                                                   41 non-null     str
 43  14. What type of Irish destination do you prefer? [Feedback]                                                0 non-null      float64
 44  15. What is your preferred way of travelling around Ireland?                                                41 non-null     str
 45  15. What is your preferred way of travelling around Ireland? [Score]                                        41 non-null     str
 46  15. What is your preferred way of travelling around Ireland? [Feedback]                                     0 non-null      float64
 47  16. What is the typical length of your leisure trip within Ireland?                                         41 non-null     str
 48  16. What is the typical length of your leisure trip within Ireland? [Score]                                 41 non-null     str
 49  16. What is the typical length of your leisure trip within Ireland? [Feedback]                              0 non-null      float64
 50  17. Which counties in Ireland have you visited for leisure?                                                 41 non-null     str
 51  17. Which counties in Ireland have you visited for leisure? [Score]                                         41 non-null     str
 52  17. Which counties in Ireland have you visited for leisure? [Feedback]                                      0 non-null      float64
 53  18. Overall, how satisfied are you with the opportunities to explore Ireland?                               41 non-null     int64
 54  18. Overall, how satisfied are you with the opportunities to explore Ireland?  [Score]                      41 non-null     str
 55  18. Overall, how satisfied are you with the opportunities to explore Ireland?  [Feedback]                   0 non-null      float64
dtypes: float64(18), int64(5), str(33)
memory usage: 32.7 KB

### 1.2 Removing inconsistent data

In [7]:
# Drop columns that contain only NA values
clean_df = df.dropna(axis=1, how="all")

# Drop [Score] columns where every value is '-- / 0'
score_cols = [c for c in clean_df.columns if c.endswith("[Score]")]

all_blank = clean_df[score_cols].apply(lambda s: s.str.strip().eq("-- / 0").all())

clean_df = clean_df.drop(columns=all_blank[all_blank].index)

# Remove 'Total score' column
clean_df = clean_df.drop(columns="Total score")

# Remove 'Unnamed: 0' column
clean_df = clean_df.drop(columns="Unnamed: 0")

# Strip spaces
text_cols = clean_df.select_dtypes(include=['object', 'string']).columns
clean_df[text_cols] = clean_df[text_cols].apply(lambda s: s.str.strip())

# Rename columns to short names
clean_df.columns = [
    "gender", "age", "years_in_ireland", "county", "living_area",
    "household", "has_car", "holiday_pref", "trips_total", "trip_type",
    "travel_with", "trip_purpose", "trips_ireland", "destination_type",
    "transport", "trip_length", "counties_visited", "satisfaction",
]

Some questions in the Google Form had an "Other:" option, so some answers were typed in by hand. These answers need to be processed.

In [8]:
# Process hand-typed answers

# the fixed options for each question that had an "Other" box
form_options = {
    'living_area':
        ['Large city', 'Small / Medium-sized town', 'Village', 'Rural area'],
    'trip_purpose':
        ['Exploring new places', 'Relaxation', 'Visiting friends and family'],
    'destination_type':
        ['A combination of these', 'Coastal areas and beaches',
         'Mountains and countryside', 'National parks and nature reserves',
         'Cities and towns', 'Historical sites and castles'],
}

def find_hand_typed(df, form_options):
    """Return every answer that is not one of the form's fixed options."""
    found = []
    for question, options in form_options.items():
        answers = df[question].dropna().str.strip()
        typed = answers[~answers.isin(options)]
        for row, answer in typed.items():
            found.append({'row': row, 'question': question, 'answer': answer})
    return pd.DataFrame(found, columns=['row', 'question', 'answer'])

hand_typed = find_hand_typed(clean_df, form_options)
hand_typed

   row          question               answer
0    9       living_area  Dublin (small city)
1   32       living_area   Small city, Dublin
2   36      trip_purpose     All of the above
3    1  destination_type               Abroad

In [9]:
# Replace hand-typed answers
recode = {
    'living_area': {
        'Dublin (small city)': 'Large city',
        'Small city, Dublin':  'Large city',
    },
    'trip_purpose': {
        'All of the above': np.nan,
    },
    'destination_type': {
        'Abroad': np.nan,
    },
}

clean_df = clean_df.replace(recode)

# Check if hand-typed values still exist
find_hand_typed(clean_df, form_options)

Empty DataFrame
Columns: [row, question, answer]
Index: []

Some respondents listed their county of residence among the counties they visited. Because the analysis is about travelling around Ireland rather than within the home county, the home county is removed from each respondent's list.

In [10]:
HOME_COL = 'county'                # Q4 - county of residence
VISITED_COL = 'counties_visited'   # Q17 - counties visited

def split_counties(answer):
    """Return the counties in one Q17 answer as a list."""
    if pd.isna(answer):
        return []
    return [c.strip() for c in answer.split(';') if c.strip() != '']

def count_listed_home(df):
    """Return how many respondents listed their home county as visited."""
    listed_home = df.apply(
        lambda row: row[HOME_COL] in split_counties(row[VISITED_COL]),
        axis=1)
    return listed_home.sum()

# Check how many respondents listed their own county as a visited county
print('Respondents who listed their home county:', count_listed_home(clean_df))

Respondents who listed their home county: 32

32 people listed their home county and 9 did not, so removing it makes the responses comparable.

In [11]:
def remove_home_county(row):
    """Return the Q17 answer without the respondent's own county."""
    kept = [c for c in split_counties(row[VISITED_COL]) if c != row[HOME_COL]]
    return ';'.join(kept)

# Remove the county of residence from the list of counties visited
clean_df[VISITED_COL] = clean_df.apply(remove_home_county, axis=1)

# Check again
print('Respondents who listed their home county:', count_listed_home(clean_df))

Respondents who listed their home county: 0

Check the dataset for duplicated rows, which may be repeat submissions from the same person.

In [12]:
# Check for duplicated rows
clean_df.duplicated().sum()

np.int64(0)

There are no exactly duplicated rows in the dataset.

Two questions in the Google Form are related and may contradict each other. Q9 asks for the total number of trips (in Ireland and abroad) and Q13 asks for the number of trips within Ireland. If a respondent answered incorrectly, the second number can be larger than the first. Such rows are flagged in an additional column. The respondents' other answers are still used, and each of the two trip counts is still analysed on its own. The flagged rows are excluded only from analyses that use both counts together, such as comparing them or calculating the share of trips taken in Ireland.

In [13]:
# Count respondents who reported more trips within Ireland than trips in total
inconsistent = clean_df['trips_ireland'] > clean_df['trips_total']

print("Inconsistent rows:", inconsistent.sum(), "of", len(clean_df))

Inconsistent rows: 5 of 41

In [14]:
# Add a column flagging inconsistent trip counts
clean_df["trips_inconsistent"] = inconsistent

Now take a look at the dataset after cleaning.

In [15]:
# Take a look at the cleaned dataset
clean_df.shape

(41, 19)

In [16]:
clean_df.head()

,gender,age,years_in_ireland,county,living_area,household,has_car,holiday_pref,trips_total,trip_type,travel_with,trip_purpose,trips_ireland,destination_type,transport,trip_length,counties_visited,satisfaction,trips_inconsistent
0,Male,27,3 - 4 years,Dublin,Large city,Sharing accommodation with friends / housemates,No,Abroad,14,Longer holidays,Partner / Spouse,Relaxation,14,Mountains and countryside,Train,4 - 7 nights,Cork;Donegal;Galway;Kerry;Kildare;Kilkenny;Lim...,5,False
1,Male,28,I was born in Ireland,Cork,Small / Medium-sized town,Living with family / children,No,Abroad,3,Weekend breaks,Alone,Relaxation,0,NaN,Combination of transport,One day/ No overnight stay,Dublin;Kildare,5,False
2,Male,55,I was born in Ireland,Donegal,Small / Medium-sized town,Living with a partner / spouse,Yes,Abroad,3,Longer holidays,Partner / Spouse,Relaxation,2,Cities and towns,Personal car,2 - 3 nights,Cork;Dublin;Galway;Kerry;Mayo;Sligo;Wexford,4,False
3,Female,29,I was born in Ireland,Mayo,Small / Medium-sized town,Living with family / children,Yes,Abroad,3,Longer holidays,Family,Exploring new places,2,A combination of these,Personal car,2 - 3 nights,Carlow;Clare;Cork;Donegal;Dublin;Galway;Kildar...,3,False
4,Female,29,I was born in Ireland,Mayo,Small / Medium-sized town,Living with family / children,Yes,Abroad,3,Longer holidays,Family,Exploring new places,2,A combination of these,Personal car,2 - 3 nights,Carlow;Clare;Cork;Donegal;Dublin;Galway;Kildar...,3,False

In [17]:
# Count unique values in each column (NaN counted as a value)
clean_df.nunique(dropna=False)

gender                 3
age                   19
years_in_ireland       7
county                10
living_area            4
household              3
has_car                2
holiday_pref           2
trips_total            9
trip_type              4
travel_with            4
trip_purpose           4
trips_ireland          8
destination_type       7
transport              5
trip_length            4
counties_visited      40
satisfaction           3
trips_inconsistent     2
dtype: int64

## 2. Add derived columns

Add a column with the number of counties visited for leisure.

In [18]:
# Number of counties visited for leisure (Q17 is multi-select, separated by ';')
def count_counties(answer):
    """Return how many counties are listed in one Q17 answer."""
    return len(split_counties(answer))

clean_df['n_counties'] = clean_df[VISITED_COL].apply(count_counties)

In [19]:
# Quick check
clean_df.head()

,gender,age,years_in_ireland,county,living_area,household,has_car,holiday_pref,trips_total,trip_type,travel_with,trip_purpose,trips_ireland,destination_type,transport,trip_length,counties_visited,satisfaction,trips_inconsistent,n_counties
0,Male,27,3 - 4 years,Dublin,Large city,Sharing accommodation with friends / housemates,No,Abroad,14,Longer holidays,Partner / Spouse,Relaxation,14,Mountains and countryside,Train,4 - 7 nights,Cork;Donegal;Galway;Kerry;Kildare;Kilkenny;Lim...,5,False,10
1,Male,28,I was born in Ireland,Cork,Small / Medium-sized town,Living with family / children,No,Abroad,3,Weekend breaks,Alone,Relaxation,0,NaN,Combination of transport,One day/ No overnight stay,Dublin;Kildare,5,False,2
2,Male,55,I was born in Ireland,Donegal,Small / Medium-sized town,Living with a partner / spouse,Yes,Abroad,3,Longer holidays,Partner / Spouse,Relaxation,2,Cities and towns,Personal car,2 - 3 nights,Cork;Dublin;Galway;Kerry;Mayo;Sligo;Wexford,4,False,7
3,Female,29,I was born in Ireland,Mayo,Small / Medium-sized town,Living with family / children,Yes,Abroad,3,Longer holidays,Family,Exploring new places,2,A combination of these,Personal car,2 - 3 nights,Carlow;Clare;Cork;Donegal;Dublin;Galway;Kildar...,3,False,14
4,Female,29,I was born in Ireland,Mayo,Small / Medium-sized town,Living with family / children,Yes,Abroad,3,Longer holidays,Family,Exploring new places,2,A combination of these,Personal car,2 - 3 nights,Carlow;Clare;Cork;Donegal;Dublin;Galway;Kildar...,3,False,13

In [20]:
print(clean_df['n_counties'].describe())

count    41.000000
mean      8.365854
std       4.784120
min       1.000000
25%       5.000000
50%       8.000000
75%      11.000000
max      19.000000
Name: n_counties, dtype: float64

Add two columns with the maximum and average travel distance within Ireland, based on the distances between county towns. Because these values do not take into account the exact places of residence and travel, they are only approximate. The distances are calculated from the latitude and longitude of each county town.

In [21]:
# Add columns with maximum and average distance of travelling inside Ireland

# Latitude and longitude of each county town (decimal degrees)
county_towns = {
    'Carlow':    (52.836, -6.926),   # Carlow
    'Cavan':     (53.991, -7.360),   # Cavan
    'Clare':     (52.843, -8.986),   # Ennis
    'Cork':      (51.898, -8.476),   # Cork
    'Donegal':   (54.833, -7.483),   # Lifford
    'Dublin':    (53.350, -6.260),   # Dublin
    'Galway':    (53.271, -9.049),   # Galway
    'Kerry':     (52.271, -9.700),   # Tralee
    'Kildare':   (53.216, -6.667),   # Naas
    'Kilkenny':  (52.654, -7.245),   # Kilkenny
    'Laois':     (53.033, -7.300),   # Portlaoise
    'Leitrim':   (53.945, -8.087),   # Carrick-on-Shannon
    'Limerick':  (52.664, -8.623),   # Limerick
    'Longford':  (53.727, -7.800),   # Longford
    'Louth':     (54.004, -6.404),   # Dundalk
    'Mayo':      (53.855, -9.298),   # Castlebar
    'Meath':     (53.653, -6.681),   # Navan
    'Monaghan':  (54.249, -6.968),   # Monaghan
    'Offaly':    (53.275, -7.493),   # Tullamore
    'Roscommon': (53.627, -8.189),   # Roscommon
    'Sligo':     (54.272, -8.476),   # Sligo
    'Tipperary': (52.862, -8.200),   # Nenagh
    'Waterford': (52.259, -7.110),   # Waterford
    'Westmeath': (53.526, -7.338),   # Mullingar
    'Wexford':   (52.336, -6.463),   # Wexford
    'Wicklow':   (52.980, -6.044),   # Wicklow
}

# Function to calculate the distance between two county towns from their latitude and longitude
def haversine_km(county_a, county_b):
    """Straight-line (great-circle) distance in km between two county towns."""
    lat1, lon1 = np.radians(county_towns[county_a])
    lat2, lon2 = np.radians(county_towns[county_b])
    a = (np.sin((lat2 - lat1) / 2) ** 2
         + np.cos(lat1) * np.cos(lat2) * np.sin((lon2 - lon1) / 2) ** 2)
    return 2 * 6371 * np.arcsin(np.sqrt(a))   # 6371 km = mean radius of the Earth

# 26 x 26 table of distances between all county towns
counties = list(county_towns)
dist_matrix = pd.DataFrame(
    [[haversine_km(a, b) for b in counties] for a in counties],
    index=counties, columns=counties).round(1)

dist_matrix.head()

,Carlow,Cavan,Clare,Cork,Donegal,Dublin,Galway,Kerry,Kildare,Kilkenny,...,Meath,Monaghan,Offaly,Roscommon,Sligo,Tipperary,Waterford,Westmeath,Wexford,Wicklow
Carlow,0.0,131.6,138.4,148.2,225.0,72.4,149.9,197.8,45.7,29.5,...,92.3,157.1,61.8,121.7,189.7,85.6,65.4,81.5,63.8,61.3
Cavan,131.6,0.0,167.0,244.4,94.0,101.6,137.2,246.9,97.6,148.9,...,58.3,38.4,80.1,67.8,79.1,137.3,193.3,51.7,193.5,142.2
Clare,138.4,167.0,0.0,110.6,242.2,190.5,47.8,79.8,160.5,119.0,...,177.8,205.5,110.7,102.0,162.4,52.8,142.5,133.5,179.5,197.9
Cork,148.2,244.4,110.6,0.0,332.9,220.1,157.5,93.4,190.9,118.7,...,229.5,280.1,166.9,193.2,264.0,108.8,101.6,196.6,145.8,204.1
Donegal,225.0,94.0,242.2,332.9,0.0,183.2,201.5,320.3,187.5,242.8,...,141.2,72.9,173.2,141.7,89.4,224.2,287.3,145.6,285.7,226.6

In [22]:
# Function to get the average and maximum distance for each respondent
def trip_distances(row):
    """Average and maximum distance from the home county to the visited counties."""
    visited = split_counties(row[VISITED_COL])
    if len(visited) == 0:
        return pd.Series([np.nan, np.nan])
    distances = dist_matrix.loc[row[HOME_COL], visited]
    return pd.Series([distances.mean(), distances.max()])

# Add the new columns
clean_df[['avg_distance_km', 'max_distance_km']] = clean_df.apply(trip_distances, axis=1).round(1)

clean_df.head()

,gender,age,years_in_ireland,county,living_area,household,has_car,holiday_pref,trips_total,trip_type,...,trips_ireland,destination_type,transport,trip_length,counties_visited,satisfaction,trips_inconsistent,n_counties,avg_distance_km,max_distance_km
0,Male,27,3 - 4 years,Dublin,Large city,Sharing accommodation with friends / housemates,No,Abroad,14,Longer holidays,...,14,Mountains and countryside,Train,4 - 7 nights,Cork;Donegal;Galway;Kerry;Kildare;Kilkenny;Lim...,5,False,10,151.3,260.4
1,Male,28,I was born in Ireland,Cork,Small / Medium-sized town,Living with family / children,No,Abroad,3,Weekend breaks,...,0,NaN,Combination of transport,One day/ No overnight stay,Dublin;Kildare,5,False,2,205.5,220.1
2,Male,55,I was born in Ireland,Donegal,Small / Medium-sized town,Living with a partner / spouse,Yes,Abroad,3,Longer holidays,...,2,Cities and towns,Personal car,2 - 3 nights,Cork;Dublin;Galway;Kerry;Mayo;Sligo;Wexford,4,False,7,224.7,332.9
3,Female,29,I was born in Ireland,Mayo,Small / Medium-sized town,Living with family / children,Yes,Abroad,3,Longer holidays,...,2,A combination of these,Personal car,2 - 3 nights,Carlow;Clare;Cork;Donegal;Dublin;Galway;Kildar...,3,False,14,158.9,236.5
4,Female,29,I was born in Ireland,Mayo,Small / Medium-sized town,Living with family / children,Yes,Abroad,3,Longer holidays,...,2,A combination of these,Personal car,2 - 3 nights,Carlow;Clare;Cork;Donegal;Dublin;Galway;Kildar...,3,False,13,156.0,229.9

Add a column with the share of leisure trips taken within Ireland (trips in Ireland divided by total trips). The share is not calculated for rows flagged as inconsistent, or where the total number of trips is zero.

In [24]:
# Check values
valid = ~clean_df['trips_inconsistent'] & (clean_df['trips_total'] > 0)

# Share of leisure trips taken within Ireland (0 = all abroad, 1 = all in Ireland)
clean_df['share_ireland'] = (
    clean_df['trips_ireland'] / clean_df['trips_total']
).where(valid).round(2)

# Quick check
print('Rows with a share:', clean_df['share_ireland'].notna().sum(), 'of', len(clean_df))
clean_df.head(10)

Rows with a share: 36 of 41

,gender,age,years_in_ireland,county,living_area,household,has_car,holiday_pref,trips_total,trip_type,...,destination_type,transport,trip_length,counties_visited,satisfaction,trips_inconsistent,n_counties,avg_distance_km,max_distance_km,share_ireland
0,Male,27,3 - 4 years,Dublin,Large city,Sharing accommodation with friends / housemates,No,Abroad,14,Longer holidays,...,Mountains and countryside,Train,4 - 7 nights,Cork;Donegal;Galway;Kerry;Kildare;Kilkenny;Lim...,5,False,10,151.3,260.4,1.00
1,Male,28,I was born in Ireland,Cork,Small / Medium-sized town,Living with family / children,No,Abroad,3,Weekend breaks,...,NaN,Combination of transport,One day/ No overnight stay,Dublin;Kildare,5,False,2,205.5,220.1,0.00
2,Male,55,I was born in Ireland,Donegal,Small / Medium-sized town,Living with a partner / spouse,Yes,Abroad,3,Longer holidays,...,Cities and towns,Personal car,2 - 3 nights,Cork;Dublin;Galway;Kerry;Mayo;Sligo;Wexford,4,False,7,224.7,332.9,0.67
3,Female,29,I was born in Ireland,Mayo,Small / Medium-sized town,Living with family / children,Yes,Abroad,3,Longer holidays,...,A combination of these,Personal car,2 - 3 nights,Carlow;Clare;Cork;Donegal;Dublin;Galway;Kildar...,3,False,14,158.9,236.5,0.67
4,Female,29,I was born in Ireland,Mayo,Small / Medium-sized town,Living with family / children,Yes,Abroad,3,Longer holidays,...,A combination of these,Personal car,2 - 3 nights,Carlow;Clare;Cork;Donegal;Dublin;Galway;Kildar...,3,False,13,156.0,229.9,0.67
5,Male,28,I was born in Ireland,Cork,Large city,Living with a partner / spouse,Yes,Abroad,5,Day trips,...,Coastal areas and beaches,Personal car,2 - 3 nights,Clare;Dublin;Galway;Kerry;Limerick;Mayo;Westme...,4,False,8,161.6,224.5,0.60
6,Female,39,5 - 6 years,Dublin,Large city,Living with a partner / spouse,No,Abroad,3,Weekend breaks,...,Coastal areas and beaches,Personal car,One day/ No overnight stay,Kildare;Kilkenny;Waterford;Wexford;Wicklow,4,False,5,84.8,134.1,1.00
7,Male,36,1 - 2 years,Mayo,Village,Sharing accommodation with friends / housemates,No,Ireland,0,Weekend breaks,...,A combination of these,Combination of transport,One day/ No overnight stay,Carlow;Cork;Donegal;Dublin;Galway;Limerick;Ros...,4,True,9,141.6,224.5,NaN
8,Male,29,3 - 4 years,Dublin,Large city,Living with a partner / spouse,No,Abroad,3,Longer holidays,...,Coastal areas and beaches,Combination of transport,2 - 3 nights,Clare;Cork;Galway;Wicklow,3,False,4,159.9,220.1,0.00
9,Female,41,More than 10 years,Dublin,Large city,Sharing accommodation with friends / housemates,Yes,Abroad,5,A combination of these,...,A combination of these,Personal car,1 night,Clare;Cork;Donegal;Galway;Kerry;Kildare;Kilken...,5,False,15,149.3,260.4,0.20
10,Male,35,9 - 10 years,Limerick,Large city,Living with a partner / spouse,Yes,Abroad,7,Longer holidays,...,National parks and nature reserves,Personal car,One day/ No overnight stay,Cavan;Clare;Cork;Dublin;Galway;Kerry;Kildare;S...,3,False,10,113.1,179.1,0.57
11,Female,36,7 - 8 years,Cork,Small / Medium-sized town,Living with family / children,Yes,Abroad,4,A combination of these,...,Coastal areas and beaches,Personal car,2 - 3 nights,Donegal;Dublin;Kerry;Kildare;Wicklow,5,False,5,208.3,332.9,0.75
12,Female,26,3 - 4 years,Dublin,Small / Medium-sized town,Sharing accommodation with friends / housemates,No,Abroad,6,Longer holidays,...,Cities and towns,Rental car,1 night,Cork;Galway;Kildare;Kilkenny;Limerick;Mayo;Sli...,3,False,8,142.9,220.1,0.33
13,Female,40,3 - 4 years,Kildare,Village,Living with family / children,No,Abroad,1,Longer holidays,...,A combination of these,Combination of transport,One day/ No overnight stay,Dublin;Waterford,3,False,2,70.7,110.5,1.00
14,Female,30,3 - 4 years,Dublin,Small / Medium-sized town,Living with a partner / spouse,No,Abroad,0,Longer holidays,...,Coastal areas and beaches,Walking/Hiking,One day/ No overnight stay,Kilkenny;Wicklow,5,True,2,72.6,101.7,NaN
15,Male,33,9 - 10 years,Dublin,Large city,Sharing accommodation with friends / housemates,Yes,Abroad,2,Longer holidays,...,Coastal areas and beaches,Personal car,2 - 3 nights,Cork;Galway;Kerry;Kildare;Wexford;Wicklow,4,False,6,142.4,260.4,0.00
16,Male,49,More than 10 years,Laois,Small / Medium-sized town,Living with family / children,Yes,Abroad,2,Longer holidays,...,Coastal areas and beaches,Personal car,2 - 3 nights,Clare;Cork;Donegal;Kerry;Kilkenny;Limerick;Mea...,4,False,11,111.2,200.5,1.00
17,Male,27,I was born in Ireland,Laois,Rural area,Living with family / children,Yes,Abroad,3,A combination of these,...,Coastal areas and beaches,Personal car,2 - 3 nights,Cork;Dublin;Galway;Sligo;Waterford;Wexford,4,False,6,114.6,158.1,0.33
18,Male,32,3 - 4 years,Dublin,Large city,Sharing accommodation with friends / housemates,No,Abroad,5,A combination of these,...,A combination of these,Rental car,One day/ No overnight stay,Cork;Galway;Kildare;Kilkenny;Waterford;Wicklow,3,False,6,119.3,220.1,0.60
19,Female,33,3 - 4 years,Dublin,Large city,Sharing accommodation with friends / housemates,Yes,Ireland,4,Weekend breaks,...,A combination of these,Personal car,One day/ No overnight stay,Carlow;Galway;Kildare;Kilkenny;Limerick;Meath;...,5,True,10,98.3,185.5,NaN
20,Male,39,3 - 4 years,Wexford,Small / Medium-sized town,Living with a partner / spouse,Yes,Abroad,4,A combination of these,...,A combination of these,Personal car,One day/ No overnight stay,Carlow;Cork;Dublin;Kerry;Kildare;Kilkenny;Lime...,4,False,9,108.7,220.2,0.50
21,Female,42,More than 10 years,Dublin,Large city,Living with a partner / spouse,Yes,Abroad,3,Longer holidays,...,Coastal areas and beaches,Personal car,2 - 3 nights,Clare;Cork;Galway;Kildare;Mayo;Wexford;Wicklow,5,False,7,141.8,220.1,1.00
22,Female,44,3 - 4 years,Dublin,Large city,Living with a partner / spouse,No,Abroad,7,Day trips,...,National parks and nature reserves,Train,One day/ No overnight stay,Cork;Kerry;Kildare,3,False,3,170.5,260.4,0.43
23,Female,36,More than 10 years,Dublin,Large city,Sharing accommodation with friends / housemates,No,Abroad,3,A combination of these,...,Mountains and countryside,Rental car,2 - 3 nights,Carlow;Clare;Cork;Donegal;Galway;Kerry;Kildare...,4,False,18,129.6,260.4,0.33
24,Male,32,I was born in Ireland,Carlow,Small / Medium-sized town,Living with a partner / spouse,Yes,Abroad,2,A combination of these,...,Coastal areas and beaches,Personal car,1 night,Clare;Cork;Donegal;Dublin;Galway;Kerry;Kilkenn...,5,True,10,140.6,225.0,NaN
25,Female,36,9 - 10 years,Cork,Small / Medium-sized town,Living with family / children,Yes,Abroad,3,Longer holidays,...,Coastal areas and beaches,Personal car,2 - 3 nights,Donegal;Kerry;Sligo,5,False,3,230.1,332.9,1.00
26,Male,36,1 - 2 years,Mayo,Large city,Sharing accommodation with friends / housemates,No,Ireland,2,Day trips,...,Mountains and countryside,Combination of transport,One day/ No overnight stay,Cork;Donegal;Dublin;Galway;Limerick;Roscommon;...,4,False,8,135.0,224.5,1.00
27,Male,40,3 - 4 years,Kildare,Rural area,Living with family / children,Yes,Abroad,2,Longer holidays,...,A combination of these,Personal car,One day/ No overnight stay,Cork;Dublin;Waterford,3,False,3,110.8,190.9,1.00
28,Non-binary,48,I was born in Ireland,Wicklow,Village,Living with family / children,Yes,Abroad,3,A combination of these,...,Coastal areas and beaches,Personal car,2 - 3 nights,Carlow;Cork;Donegal;Dublin;Galway;Kerry;Kildar...,3,False,14,130.6,259.0,0.33
29,Female,26,5 - 6 years,Dublin,Small / Medium-sized town,Living with a partner / spouse,Yes,Abroad,2,Weekend breaks,...,A combination of these,Personal car,1 night,Carlow;Cavan;Cork;Galway;Kildare;Limerick;Mayo...,4,True,8,129.7,220.1,NaN
30,Male,32,3 - 4 years,Dublin,Large city,Sharing accommodation with friends / housemates,No,Abroad,5,A combination of these,...,A combination of these,Rental car,One day/ No overnight stay,Cork;Galway;Kildare;Kilkenny;Limerick;Mayo;Mea...,5,False,11,130.4,220.1,0.60
31,Male,33,9 - 10 years,Dublin,Small / Medium-sized town,Sharing accommodation with friends / housemates,Yes,Abroad,2,Longer holidays,...,Coastal areas and beaches,Personal car,2 - 3 nights,Kerry;Kildare;Wicklow,3,False,3,111.6,260.4,0.50
32,Female,41,More than 10 years,Dublin,Large city,Sharing accommodation with friends / housemates,Yes,Abroad,5,A combination of these,...,A combination of these,Personal car,2 - 3 nights,Cavan;Clare;Cork;Donegal;Galway;Kerry;Kildare;...,5,False,19,138.7,260.4,0.20
33,Female,31,More than 10 years,Cork,Village,Living with family / children,Yes,Abroad,3,Longer holidays,...,A combination of these,Personal car,1 night,Dublin;Galway;Kerry;Kilkenny;Limerick;Sligo;Wa...,5,False,8,148.4,264.0,0.00
34,Male,27,3 - 4 years,Dublin,Large city,Living with a partner / spouse,Yes,Abroad,3,Longer holidays,...,Coastal areas and beaches,Personal car,One day/ No overnight stay,Clare;Cork;Donegal;Kerry;Kilkenny;Mayo;Waterfo...,3,False,9,161.7,260.4,0.33
35,Female,29,I was born in Ireland,Mayo,Small / Medium-sized town,Living with family / children,Yes,Abroad,3,A combination of these,...,A combination of these,Personal car,2 - 3 nights,Carlow;Clare;Cork;Donegal;Dublin;Galway;Kilken...,3,False,15,149.9,236.5,0.67
36,Female,43,More than 10 years,Dublin,Large city,Living with family / children,Yes,Abroad,5,A combination of these,...,A combination of these,Personal car,1 night,Clare;Cork;Donegal;Galway;Kerry;Kildare;Kilken...,5,False,16,138.2,260.4,0.60
37,Male,30,3 - 4 years,Dublin,Large city,Living with a partner / spouse,Yes,Abroad,2,Longer holidays,...,National parks and nature reserves,Personal car,One day/ No overnight stay,Wicklow,3,False,1,43.6,43.6,0.00
38,Male,35,More than 10 years,Dublin,Large city,Living with a partner / spouse,No,Abroad,3,Longer holidays,...,A combination of these,Combination of transport,2 - 3 nights,Kerry,5,False,1,260.4,260.4,1.00
39,Female,26,I was born in Ireland,Cork,Large city,Sharing accommodation with friends / housemates,No,Abroad,5,Longer holidays,...,Historical sites and castles,Train,One day/ No overnight stay,Clare;Dublin;Galway;Kerry;Kildare;Leitrim;Lime...,5,False,15,170.1,264.0,0.40
40,Male,39,3 - 4 years,Wexford,Small / Medium-sized town,Living with a partner / spouse,Yes,Abroad,5,A combination of these,...,A combination of these,Personal car,One day/ No overnight stay,Carlow;Cork;Dublin;Kerry;Kildare;Kilkenny;Lime...,4,False,9,108.7,220.2,0.40

### 3. Descriptive analysis

In [26]:
clean_df.to_csv('new.csv')